<?php

namespace Nieruchomosci\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KomunikacjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomunikacjaRepository extends EntityRepository
{
}
