<?php

namespace Nieruchomosci\Repository;

use Doctrine\ORM\EntityRepository;
use Nieruchomosci\Entity\Mieszkanie;

/**
 * MieszkanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MieszkanieRepository extends EntityRepository
{

    public function pobierzWszystko()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('m')
                ->from(Mieszkanie::class, 'm')
                ->join('m.nieruchomosc', 'n');

        return $qb->getQuery()->getResult();
    }

}
