<?php

namespace DoctrineORMModule\Proxy\__CG__\Nieruchomosci\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nieruchomosc extends \Nieruchomosci\Entity\Nieruchomosc implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'id', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'typ_oferty', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'powierzchnia', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'cena', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'cena_m2', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'mieszkanie', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'miasto', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'opcjekomunikacji'];
        }

        return ['__isInitialized__', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'id', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'typ_oferty', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'powierzchnia', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'cena', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'cena_m2', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'mieszkanie', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'miasto', '' . "\0" . 'Nieruchomosci\\Entity\\Nieruchomosc' . "\0" . 'opcjekomunikacji'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nieruchomosc $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypOferty(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypOferty', []);

        return parent::getTypOferty();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypOferty(string $typ_oferty): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypOferty', [$typ_oferty]);

        return parent::setTypOferty($typ_oferty);
    }

    /**
     * {@inheritDoc}
     */
    public function getPowierzchnia(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPowierzchnia', []);

        return parent::getPowierzchnia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPowierzchnia(float $powierzchnia): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPowierzchnia', [$powierzchnia]);

        return parent::setPowierzchnia($powierzchnia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCena(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCena', []);

        return parent::getCena();
    }

    /**
     * {@inheritDoc}
     */
    public function setCena(int $cena): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCena', [$cena]);

        return parent::setCena($cena);
    }

    /**
     * {@inheritDoc}
     */
    public function getCenaM2(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCenaM2', []);

        return parent::getCenaM2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCenaM2(float $cena_m2): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCenaM2', [$cena_m2]);

        return parent::setCenaM2($cena_m2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMieszkanie(): ?\Nieruchomosci\Entity\Mieszkanie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMieszkanie', []);

        return parent::getMieszkanie();
    }

    /**
     * {@inheritDoc}
     */
    public function setMieszkanie(\Nieruchomosci\Entity\Mieszkanie $mieszkanie): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMieszkanie', [$mieszkanie]);

        return parent::setMieszkanie($mieszkanie);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiasto(): ?\Nieruchomosci\Entity\Miasto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiasto', []);

        return parent::getMiasto();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiasto(\Nieruchomosci\Entity\Miasto $miasto): \Nieruchomosci\Entity\Nieruchomosc
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiasto', [$miasto]);

        return parent::setMiasto($miasto);
    }

    /**
     * {@inheritDoc}
     */
    public function addOpcjekomunikacji($opcjeKomunikacji)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOpcjekomunikacji', [$opcjeKomunikacji]);

        return parent::addOpcjekomunikacji($opcjeKomunikacji);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOpcjekomunikacji($opcjeKomunikacji)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOpcjekomunikacji', [$opcjeKomunikacji]);

        return parent::removeOpcjekomunikacji($opcjeKomunikacji);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpcjekomunikacji()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpcjekomunikacji', []);

        return parent::getOpcjekomunikacji();
    }

    /**
     * {@inheritDoc}
     */
    public function pobierzKomunikacje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pobierzKomunikacje', []);

        return parent::pobierzKomunikacje();
    }

}
